# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ryu\Desktop\Airline Reservation System\UI\admin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(770, 662)
        self.gridLayout = QtWidgets.QGridLayout(AdminWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(AdminWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabStatus = QtWidgets.QWidget()
        self.tabStatus.setObjectName("tabStatus")
        self.gbFlightDetails = QtWidgets.QGroupBox(self.tabStatus)
        self.gbFlightDetails.setGeometry(QtCore.QRect(260, 30, 471, 321))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gbFlightDetails.setFont(font)
        self.gbFlightDetails.setObjectName("gbFlightDetails")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.gbFlightDetails)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 154, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout.addWidget(self.label_26)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.gbFlightDetails)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 40, 181, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblOrigin = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblOrigin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblOrigin.setObjectName("lblOrigin")
        self.verticalLayout_3.addWidget(self.lblOrigin)
        self.lblDestination = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblDestination.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDestination.setObjectName("lblDestination")
        self.verticalLayout_3.addWidget(self.lblDestination)
        self.lblTravelDate = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblTravelDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTravelDate.setObjectName("lblTravelDate")
        self.verticalLayout_3.addWidget(self.lblTravelDate)
        self.lblPrice = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblPrice.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPrice.setObjectName("lblPrice")
        self.verticalLayout_3.addWidget(self.lblPrice)
        self.lblAvailSeats = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblAvailSeats.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAvailSeats.setObjectName("lblAvailSeats")
        self.verticalLayout_3.addWidget(self.lblAvailSeats)
        self.txtRemarks = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.txtRemarks.setObjectName("txtRemarks")
        self.verticalLayout_3.addWidget(self.txtRemarks)
        self.btnUpdateFlight = QtWidgets.QPushButton(self.gbFlightDetails)
        self.btnUpdateFlight.setGeometry(QtCore.QRect(370, 270, 91, 31))
        self.btnUpdateFlight.setObjectName("btnUpdateFlight")
        self.btnDeleteFlight = QtWidgets.QPushButton(self.tabStatus)
        self.btnDeleteFlight.setGeometry(QtCore.QRect(260, 360, 131, 41))
        self.btnDeleteFlight.setObjectName("btnDeleteFlight")
        self.label = QtWidgets.QLabel(self.tabStatus)
        self.label.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.label.setObjectName("label")
        self.lstFlights = QtWidgets.QListWidget(self.tabStatus)
        self.lstFlights.setGeometry(QtCore.QRect(20, 40, 231, 541))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstFlights.setFont(font)
        self.lstFlights.setObjectName("lstFlights")
        self.tabWidget.addTab(self.tabStatus, "")
        self.tabBook = QtWidgets.QWidget()
        self.tabBook.setObjectName("tabBook")
        self.lstPassengers = QtWidgets.QListWidget(self.tabBook)
        self.lstPassengers.setGeometry(QtCore.QRect(20, 90, 221, 491))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstPassengers.setFont(font)
        self.lstPassengers.setObjectName("lstPassengers")
        self.label_3 = QtWidgets.QLabel(self.tabBook)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 61, 31))
        self.label_3.setObjectName("label_3")
        self.cbxFlightPassengers = QtWidgets.QComboBox(self.tabBook)
        self.cbxFlightPassengers.setGeometry(QtCore.QRect(100, 10, 241, 31))
        self.cbxFlightPassengers.setObjectName("cbxFlightPassengers")
        self.gbFlightDetails_2 = QtWidgets.QGroupBox(self.tabBook)
        self.gbFlightDetails_2.setGeometry(QtCore.QRect(260, 80, 391, 261))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gbFlightDetails_2.setFont(font)
        self.gbFlightDetails_2.setObjectName("gbFlightDetails_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.gbFlightDetails_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 40, 113, 201))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_4.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_4.addWidget(self.label_29)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.gbFlightDetails_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(150, 40, 221, 201))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblFName = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lblFName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFName.setObjectName("lblFName")
        self.verticalLayout_5.addWidget(self.lblFName)
        self.lblLName = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lblLName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLName.setObjectName("lblLName")
        self.verticalLayout_5.addWidget(self.lblLName)
        self.lblGender = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lblGender.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblGender.setObjectName("lblGender")
        self.verticalLayout_5.addWidget(self.lblGender)
        self.lblAge = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lblAge.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAge.setObjectName("lblAge")
        self.verticalLayout_5.addWidget(self.lblAge)
        self.label_4 = QtWidgets.QLabel(self.tabBook)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 111, 31))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tabBook, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.btnDeleteUser = QtWidgets.QPushButton(self.tab_3)
        self.btnDeleteUser.setGeometry(QtCore.QRect(240, 450, 171, 31))
        self.btnDeleteUser.setObjectName("btnDeleteUser")
        self.lstUsers = QtWidgets.QListWidget(self.tab_3)
        self.lstUsers.setGeometry(QtCore.QRect(20, 40, 201, 551))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstUsers.setFont(font)
        self.lstUsers.setObjectName("lstUsers")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.label_8.setObjectName("label_8")
        self.gbFlightDetails_3 = QtWidgets.QGroupBox(self.tab_3)
        self.gbFlightDetails_3.setGeometry(QtCore.QRect(240, 30, 491, 411))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gbFlightDetails_3.setFont(font)
        self.gbFlightDetails_3.setObjectName("gbFlightDetails_3")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.gbFlightDetails_3)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 30, 241, 361))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_6.addWidget(self.label_36)
        self.lblUsername = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUsername.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUsername.setObjectName("lblUsername")
        self.verticalLayout_6.addWidget(self.lblUsername)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.lblUserFName = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUserFName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUserFName.setObjectName("lblUserFName")
        self.verticalLayout_6.addWidget(self.lblUserFName)
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_6.addWidget(self.label_30)
        self.lblUserLName = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUserLName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUserLName.setObjectName("lblUserLName")
        self.verticalLayout_6.addWidget(self.lblUserLName)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.lblEmail = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblEmail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEmail.setObjectName("lblEmail")
        self.verticalLayout_6.addWidget(self.lblEmail)
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.lblAddress = QtWidgets.QTextBrowser(self.verticalLayoutWidget_5)
        self.lblAddress.setObjectName("lblAddress")
        self.verticalLayout_6.addWidget(self.lblAddress)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.gbFlightDetails_3)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(270, 30, 211, 201))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_2.addWidget(self.label_34)
        self.lblUserGender = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.lblUserGender.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUserGender.setObjectName("lblUserGender")
        self.verticalLayout_2.addWidget(self.lblUserGender)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_2.addWidget(self.label_33)
        self.lblBirthDate = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.lblBirthDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblBirthDate.setObjectName("lblBirthDate")
        self.verticalLayout_2.addWidget(self.lblBirthDate)
        self.label_35 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_2.addWidget(self.label_35)
        self.lblNum = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.lblNum.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblNum.setObjectName("lblNum")
        self.verticalLayout_2.addWidget(self.lblNum)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(AdminWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "Admin Window"))
        self.gbFlightDetails.setTitle(_translate("AdminWindow", "Flight Details"))
        self.label_5.setText(_translate("AdminWindow", "Origin:"))
        self.label_23.setText(_translate("AdminWindow", "Destination:"))
        self.label_22.setText(_translate("AdminWindow", "Travel Date:"))
        self.label_24.setText(_translate("AdminWindow", "Price:"))
        self.label_25.setText(_translate("AdminWindow", "Available Seats:"))
        self.label_26.setText(_translate("AdminWindow", "Remarks:"))
        self.lblOrigin.setText(_translate("AdminWindow", "<origin>"))
        self.lblDestination.setText(_translate("AdminWindow", "<destination>"))
        self.lblTravelDate.setText(_translate("AdminWindow", "<travel date>"))
        self.lblPrice.setText(_translate("AdminWindow", "<price>"))
        self.lblAvailSeats.setText(_translate("AdminWindow", "<available seats>"))
        self.btnUpdateFlight.setText(_translate("AdminWindow", "Update"))
        self.btnDeleteFlight.setText(_translate("AdminWindow", "Delete Flight"))
        self.label.setText(_translate("AdminWindow", "Flights:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("AdminWindow", "Manage Flights"))
        self.label_3.setText(_translate("AdminWindow", "Flights:"))
        self.gbFlightDetails_2.setTitle(_translate("AdminWindow", "Passenger Details:"))
        self.label_6.setText(_translate("AdminWindow", "First Name:"))
        self.label_27.setText(_translate("AdminWindow", "Last Name:"))
        self.label_28.setText(_translate("AdminWindow", "Gender:"))
        self.label_29.setText(_translate("AdminWindow", "Age:"))
        self.lblFName.setText(_translate("AdminWindow", "<Fname>"))
        self.lblLName.setText(_translate("AdminWindow", "<Lname>"))
        self.lblGender.setText(_translate("AdminWindow", "<Gender>"))
        self.lblAge.setText(_translate("AdminWindow", "<Age>"))
        self.label_4.setText(_translate("AdminWindow", "Passengers:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBook), _translate("AdminWindow", "Manage Passengers"))
        self.btnDeleteUser.setText(_translate("AdminWindow", "Delete User"))
        self.label_8.setText(_translate("AdminWindow", "Users:"))
        self.gbFlightDetails_3.setTitle(_translate("AdminWindow", "User Details:"))
        self.label_36.setText(_translate("AdminWindow", "Username:"))
        self.lblUsername.setText(_translate("AdminWindow", "<username>"))
        self.label_7.setText(_translate("AdminWindow", "First Name:"))
        self.lblUserFName.setText(_translate("AdminWindow", "<Fname>"))
        self.label_30.setText(_translate("AdminWindow", "Last Name:"))
        self.lblUserLName.setText(_translate("AdminWindow", "<Lname>"))
        self.label_31.setText(_translate("AdminWindow", "Email:"))
        self.lblEmail.setText(_translate("AdminWindow", "<Email>"))
        self.label_32.setText(_translate("AdminWindow", "Address:"))
        self.label_34.setText(_translate("AdminWindow", "Gender:"))
        self.lblUserGender.setText(_translate("AdminWindow", "<Gender>"))
        self.label_33.setText(_translate("AdminWindow", "Birth Date:"))
        self.lblBirthDate.setText(_translate("AdminWindow", "<Birthday>"))
        self.label_35.setText(_translate("AdminWindow", "Contact Number:"))
        self.lblNum.setText(_translate("AdminWindow", "<Contact Num>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("AdminWindow", "Manage Users"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminWindow = QtWidgets.QDialog()
    ui = Ui_AdminWindow()
    ui.setupUi(AdminWindow)
    AdminWindow.show()
    sys.exit(app.exec_())

