# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ryu\Desktop\Airline Reservation System\UI\admin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(770, 663)
        self.gridLayout = QtWidgets.QGridLayout(AdminWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(AdminWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabStatus = QtWidgets.QWidget()
        self.tabStatus.setObjectName("tabStatus")
        self.gbFlightDetails = QtWidgets.QGroupBox(self.tabStatus)
        self.gbFlightDetails.setGeometry(QtCore.QRect(260, 10, 471, 301))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gbFlightDetails.setFont(font)
        self.gbFlightDetails.setObjectName("gbFlightDetails")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbFlightDetails)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.gbFlightDetails)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_23 = QtWidgets.QLabel(self.gbFlightDetails)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_22 = QtWidgets.QLabel(self.gbFlightDetails)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_24 = QtWidgets.QLabel(self.gbFlightDetails)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtWidgets.QLabel(self.gbFlightDetails)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtWidgets.QLabel(self.gbFlightDetails)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.lblOrigin = QtWidgets.QLabel(self.gbFlightDetails)
        self.lblOrigin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblOrigin.setObjectName("lblOrigin")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblOrigin)
        self.lblDestination = QtWidgets.QLabel(self.gbFlightDetails)
        self.lblDestination.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDestination.setObjectName("lblDestination")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblDestination)
        self.lblTravelDate = QtWidgets.QLabel(self.gbFlightDetails)
        self.lblTravelDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTravelDate.setObjectName("lblTravelDate")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblTravelDate)
        self.lblPrice = QtWidgets.QLabel(self.gbFlightDetails)
        self.lblPrice.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPrice.setObjectName("lblPrice")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lblPrice)
        self.lblAvailSeats = QtWidgets.QLabel(self.gbFlightDetails)
        self.lblAvailSeats.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAvailSeats.setObjectName("lblAvailSeats")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lblAvailSeats)
        self.txtRemarks = QtWidgets.QLineEdit(self.gbFlightDetails)
        self.txtRemarks.setObjectName("txtRemarks")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txtRemarks)
        self.label_42 = QtWidgets.QLabel(self.gbFlightDetails)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.lblTravelTime = QtWidgets.QLabel(self.gbFlightDetails)
        self.lblTravelTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTravelTime.setObjectName("lblTravelTime")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lblTravelTime)
        self.gridLayout_4.addLayout(self.formLayout_3, 0, 0, 1, 2)
        self.btnUpdateFlight = QtWidgets.QPushButton(self.gbFlightDetails)
        self.btnUpdateFlight.setObjectName("btnUpdateFlight")
        self.gridLayout_4.addWidget(self.btnUpdateFlight, 1, 0, 1, 1)
        self.btnDeleteFlight = QtWidgets.QPushButton(self.gbFlightDetails)
        self.btnDeleteFlight.setObjectName("btnDeleteFlight")
        self.gridLayout_4.addWidget(self.btnDeleteFlight, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tabStatus)
        self.label.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.label.setObjectName("label")
        self.lstFlights = QtWidgets.QListWidget(self.tabStatus)
        self.lstFlights.setGeometry(QtCore.QRect(20, 40, 231, 551))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstFlights.setFont(font)
        self.lstFlights.setObjectName("lstFlights")
        self.gbFlightDetails_4 = QtWidgets.QGroupBox(self.tabStatus)
        self.gbFlightDetails_4.setGeometry(QtCore.QRect(260, 327, 471, 271))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gbFlightDetails_4.setFont(font)
        self.gbFlightDetails_4.setObjectName("gbFlightDetails_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbFlightDetails_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnAddFlight = QtWidgets.QPushButton(self.gbFlightDetails_4)
        self.btnAddFlight.setObjectName("btnAddFlight")
        self.gridLayout_2.addWidget(self.btnAddFlight, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.gbFlightDetails_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbxOriginCountry = QtWidgets.QComboBox(self.gbFlightDetails_4)
        self.cbxOriginCountry.setObjectName("cbxOriginCountry")
        self.horizontalLayout.addWidget(self.cbxOriginCountry)
        self.cbxOriginCity = QtWidgets.QComboBox(self.gbFlightDetails_4)
        self.cbxOriginCity.setObjectName("cbxOriginCity")
        self.horizontalLayout.addWidget(self.cbxOriginCity)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_37 = QtWidgets.QLabel(self.gbFlightDetails_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbxDestinationCountry = QtWidgets.QComboBox(self.gbFlightDetails_4)
        self.cbxDestinationCountry.setObjectName("cbxDestinationCountry")
        self.horizontalLayout_2.addWidget(self.cbxDestinationCountry)
        self.cbxDestinationCity = QtWidgets.QComboBox(self.gbFlightDetails_4)
        self.cbxDestinationCity.setObjectName("cbxDestinationCity")
        self.horizontalLayout_2.addWidget(self.cbxDestinationCity)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_38 = QtWidgets.QLabel(self.gbFlightDetails_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.label_40 = QtWidgets.QLabel(self.gbFlightDetails_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.label_39 = QtWidgets.QLabel(self.gbFlightDetails_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.txtPrice = QtWidgets.QLineEdit(self.gbFlightDetails_4)
        self.txtPrice.setObjectName("txtPrice")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txtPrice)
        self.txtTravelDate = QtWidgets.QDateEdit(self.gbFlightDetails_4)
        self.txtTravelDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 10, 12), QtCore.QTime(0, 0, 0)))
        self.txtTravelDate.setObjectName("txtTravelDate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtTravelDate)
        self.txtTravelTime = QtWidgets.QTimeEdit(self.gbFlightDetails_4)
        self.txtTravelTime.setObjectName("txtTravelTime")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtTravelTime)
        self.label_43 = QtWidgets.QLabel(self.gbFlightDetails_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.txtSeats = QtWidgets.QLineEdit(self.gbFlightDetails_4)
        self.txtSeats.setObjectName("txtSeats")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtSeats)
        self.gridLayout_2.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabStatus, "")
        self.tabBook = QtWidgets.QWidget()
        self.tabBook.setObjectName("tabBook")
        self.lstPassengers = QtWidgets.QListWidget(self.tabBook)
        self.lstPassengers.setGeometry(QtCore.QRect(20, 100, 221, 481))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstPassengers.setFont(font)
        self.lstPassengers.setObjectName("lstPassengers")
        self.label_3 = QtWidgets.QLabel(self.tabBook)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 61, 31))
        self.label_3.setObjectName("label_3")
        self.cbxFlightPassengers = QtWidgets.QComboBox(self.tabBook)
        self.cbxFlightPassengers.setGeometry(QtCore.QRect(100, 10, 241, 31))
        self.cbxFlightPassengers.setObjectName("cbxFlightPassengers")
        self.gbFlightDetails_2 = QtWidgets.QGroupBox(self.tabBook)
        self.gbFlightDetails_2.setGeometry(QtCore.QRect(260, 90, 421, 201))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gbFlightDetails_2.setFont(font)
        self.gbFlightDetails_2.setObjectName("gbFlightDetails_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbFlightDetails_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gbFlightDetails_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_27 = QtWidgets.QLabel(self.gbFlightDetails_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.label_28 = QtWidgets.QLabel(self.gbFlightDetails_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.label_29 = QtWidgets.QLabel(self.gbFlightDetails_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.lblFName = QtWidgets.QLabel(self.gbFlightDetails_2)
        self.lblFName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFName.setObjectName("lblFName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblFName)
        self.lblLName = QtWidgets.QLabel(self.gbFlightDetails_2)
        self.lblLName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLName.setObjectName("lblLName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblLName)
        self.lblGender = QtWidgets.QLabel(self.gbFlightDetails_2)
        self.lblGender.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblGender.setObjectName("lblGender")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblGender)
        self.lblAge = QtWidgets.QLabel(self.gbFlightDetails_2)
        self.lblAge.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAge.setObjectName("lblAge")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lblAge)
        self.gridLayout_3.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tabBook)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 111, 31))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.tabBook, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.btnDeleteUser = QtWidgets.QPushButton(self.tab_3)
        self.btnDeleteUser.setGeometry(QtCore.QRect(240, 450, 171, 31))
        self.btnDeleteUser.setObjectName("btnDeleteUser")
        self.lstUsers = QtWidgets.QListWidget(self.tab_3)
        self.lstUsers.setGeometry(QtCore.QRect(20, 40, 201, 551))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstUsers.setFont(font)
        self.lstUsers.setObjectName("lstUsers")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.label_8.setObjectName("label_8")
        self.gbFlightDetails_3 = QtWidgets.QGroupBox(self.tab_3)
        self.gbFlightDetails_3.setGeometry(QtCore.QRect(240, 30, 491, 411))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gbFlightDetails_3.setFont(font)
        self.gbFlightDetails_3.setObjectName("gbFlightDetails_3")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.gbFlightDetails_3)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 30, 241, 361))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_6.addWidget(self.label_36)
        self.lblUsername = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUsername.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUsername.setObjectName("lblUsername")
        self.verticalLayout_6.addWidget(self.lblUsername)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.lblUserFName = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUserFName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUserFName.setObjectName("lblUserFName")
        self.verticalLayout_6.addWidget(self.lblUserFName)
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_6.addWidget(self.label_30)
        self.lblUserLName = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUserLName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUserLName.setObjectName("lblUserLName")
        self.verticalLayout_6.addWidget(self.lblUserLName)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.lblEmail = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblEmail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEmail.setObjectName("lblEmail")
        self.verticalLayout_6.addWidget(self.lblEmail)
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.lblAddress = QtWidgets.QTextBrowser(self.verticalLayoutWidget_5)
        self.lblAddress.setObjectName("lblAddress")
        self.verticalLayout_6.addWidget(self.lblAddress)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.gbFlightDetails_3)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(270, 30, 211, 201))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_2.addWidget(self.label_34)
        self.lblUserGender = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.lblUserGender.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUserGender.setObjectName("lblUserGender")
        self.verticalLayout_2.addWidget(self.lblUserGender)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_2.addWidget(self.label_33)
        self.lblBirthDate = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.lblBirthDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblBirthDate.setObjectName("lblBirthDate")
        self.verticalLayout_2.addWidget(self.lblBirthDate)
        self.label_35 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_2.addWidget(self.label_35)
        self.lblNum = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.lblNum.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblNum.setObjectName("lblNum")
        self.verticalLayout_2.addWidget(self.lblNum)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_6)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(17, 29, 421, 181))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.txtCurrentUsername = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.txtCurrentUsername.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.txtCurrentUsername.setObjectName("txtCurrentUsername")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtCurrentUsername)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.txtNewUsername = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.txtNewUsername.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.txtNewUsername.setObjectName("txtNewUsername")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtNewUsername)
        self.btnChangeUsername = QtWidgets.QPushButton(self.formLayoutWidget_4)
        self.btnChangeUsername.setObjectName("btnChangeUsername")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btnChangeUsername)
        self.gridLayout_5.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_5)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(20, 40, 421, 181))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.txtCurrentPassword = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.txtCurrentPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtCurrentPassword.setObjectName("txtCurrentPassword")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtCurrentPassword)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.txtNewPassword = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.txtNewPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtNewPassword.setObjectName("txtNewPassword")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtNewPassword)
        self.label_41 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.txtConfirmPassword = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.txtConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtConfirmPassword)
        self.btnChangePassword = QtWidgets.QPushButton(self.formLayoutWidget_5)
        self.btnChangePassword.setObjectName("btnChangePassword")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.btnChangePassword)
        self.gridLayout_5.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.retranslateUi(AdminWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "Admin Window"))
        self.gbFlightDetails.setTitle(_translate("AdminWindow", "Flight Details"))
        self.label_5.setText(_translate("AdminWindow", "Origin:"))
        self.label_23.setText(_translate("AdminWindow", "Destination:"))
        self.label_22.setText(_translate("AdminWindow", "Travel Date:"))
        self.label_24.setText(_translate("AdminWindow", "Price:"))
        self.label_25.setText(_translate("AdminWindow", "Available Seats:"))
        self.label_26.setText(_translate("AdminWindow", "Remarks:"))
        self.lblOrigin.setText(_translate("AdminWindow", "<origin>"))
        self.lblDestination.setText(_translate("AdminWindow", "<destination>"))
        self.lblTravelDate.setText(_translate("AdminWindow", "<travel date>"))
        self.lblPrice.setText(_translate("AdminWindow", "<price>"))
        self.lblAvailSeats.setText(_translate("AdminWindow", "<available seats>"))
        self.label_42.setText(_translate("AdminWindow", "Travel Time:"))
        self.lblTravelTime.setText(_translate("AdminWindow", "<travel time>"))
        self.btnUpdateFlight.setText(_translate("AdminWindow", "Update Flight"))
        self.btnDeleteFlight.setText(_translate("AdminWindow", "Delete Flight"))
        self.label.setText(_translate("AdminWindow", "Flights:"))
        self.gbFlightDetails_4.setTitle(_translate("AdminWindow", "Add a Flight"))
        self.btnAddFlight.setText(_translate("AdminWindow", "Add Flight"))
        self.label_9.setText(_translate("AdminWindow", "Origin:"))
        self.label_37.setText(_translate("AdminWindow", "Destination:"))
        self.label_38.setText(_translate("AdminWindow", "Travel Date:"))
        self.label_40.setText(_translate("AdminWindow", "Travel Time:"))
        self.label_39.setText(_translate("AdminWindow", "Price:"))
        self.label_43.setText(_translate("AdminWindow", "Seats:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("AdminWindow", "Manage Flights"))
        self.label_3.setText(_translate("AdminWindow", "Flights:"))
        self.gbFlightDetails_2.setTitle(_translate("AdminWindow", "Passenger Details:"))
        self.label_6.setText(_translate("AdminWindow", "First Name:"))
        self.label_27.setText(_translate("AdminWindow", "Last Name:"))
        self.label_28.setText(_translate("AdminWindow", "Gender:"))
        self.label_29.setText(_translate("AdminWindow", "Age:"))
        self.lblFName.setText(_translate("AdminWindow", "<Fname>"))
        self.lblLName.setText(_translate("AdminWindow", "<Lname>"))
        self.lblGender.setText(_translate("AdminWindow", "<Gender>"))
        self.lblAge.setText(_translate("AdminWindow", "<Age>"))
        self.label_4.setText(_translate("AdminWindow", "Passengers:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBook), _translate("AdminWindow", "Manage Passengers"))
        self.btnDeleteUser.setText(_translate("AdminWindow", "Delete User"))
        self.label_8.setText(_translate("AdminWindow", "Users:"))
        self.gbFlightDetails_3.setTitle(_translate("AdminWindow", "User Details:"))
        self.label_36.setText(_translate("AdminWindow", "Username:"))
        self.lblUsername.setText(_translate("AdminWindow", "<username>"))
        self.label_7.setText(_translate("AdminWindow", "First Name:"))
        self.lblUserFName.setText(_translate("AdminWindow", "<Fname>"))
        self.label_30.setText(_translate("AdminWindow", "Last Name:"))
        self.lblUserLName.setText(_translate("AdminWindow", "<Lname>"))
        self.label_31.setText(_translate("AdminWindow", "Email:"))
        self.lblEmail.setText(_translate("AdminWindow", "<Email>"))
        self.label_32.setText(_translate("AdminWindow", "Address:"))
        self.label_34.setText(_translate("AdminWindow", "Gender:"))
        self.lblUserGender.setText(_translate("AdminWindow", "<Gender>"))
        self.label_33.setText(_translate("AdminWindow", "Birth Date:"))
        self.lblBirthDate.setText(_translate("AdminWindow", "<Birthday>"))
        self.label_35.setText(_translate("AdminWindow", "Contact Number:"))
        self.lblNum.setText(_translate("AdminWindow", "<Contact Num>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("AdminWindow", "Manage Users"))
        self.groupBox_6.setTitle(_translate("AdminWindow", "Change Username"))
        self.label_11.setText(_translate("AdminWindow", "Current Username:"))
        self.label_19.setText(_translate("AdminWindow", "New Username:"))
        self.btnChangeUsername.setText(_translate("AdminWindow", "Change Username"))
        self.groupBox_5.setTitle(_translate("AdminWindow", "Change Password:"))
        self.label_12.setText(_translate("AdminWindow", "Current Password:"))
        self.label_21.setText(_translate("AdminWindow", "New Password:"))
        self.label_41.setText(_translate("AdminWindow", "Confirm Password:"))
        self.btnChangePassword.setText(_translate("AdminWindow", "Change Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("AdminWindow", "Manage Admin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminWindow = QtWidgets.QDialog()
    ui = Ui_AdminWindow()
    ui.setupUi(AdminWindow)
    AdminWindow.show()
    sys.exit(app.exec_())

