# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ryu\Desktop\Airline Reservation System\UI\customer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CustomerWindow(object):
    def setupUi(self, CustomerWindow):
        CustomerWindow.setObjectName("CustomerWindow")
        CustomerWindow.resize(858, 485)
        self.gridLayout = QtWidgets.QGridLayout(CustomerWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(CustomerWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabBook = QtWidgets.QWidget()
        self.tabBook.setObjectName("tabBook")
        self.groupBox = QtWidgets.QGroupBox(self.tabBook)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 171))
        self.groupBox.setObjectName("groupBox")
        self.cbxOriginCity = QtWidgets.QComboBox(self.groupBox)
        self.cbxOriginCity.setGeometry(QtCore.QRect(20, 120, 341, 31))
        self.cbxOriginCity.setObjectName("cbxOriginCity")
        self.cbxOriginCountry = QtWidgets.QComboBox(self.groupBox)
        self.cbxOriginCountry.setGeometry(QtCore.QRect(20, 60, 341, 31))
        self.cbxOriginCountry.setObjectName("cbxOriginCountry")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabBook)
        self.groupBox_2.setGeometry(QtCore.QRect(420, 10, 391, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cbxDestinationCity = QtWidgets.QComboBox(self.groupBox_2)
        self.cbxDestinationCity.setGeometry(QtCore.QRect(20, 120, 341, 31))
        self.cbxDestinationCity.setObjectName("cbxDestinationCity")
        self.cbxDestinationCountry = QtWidgets.QComboBox(self.groupBox_2)
        self.cbxDestinationCountry.setGeometry(QtCore.QRect(20, 60, 341, 31))
        self.cbxDestinationCountry.setObjectName("cbxDestinationCountry")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabBook)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 190, 391, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.txtDate = QtWidgets.QDateEdit(self.groupBox_3)
        self.txtDate.setGeometry(QtCore.QRect(100, 40, 211, 31))
        self.txtDate.setObjectName("txtDate")
        self.cbxTime = QtWidgets.QComboBox(self.groupBox_3)
        self.cbxTime.setGeometry(QtCore.QRect(100, 90, 211, 31))
        self.cbxTime.setObjectName("cbxTime")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabBook)
        self.groupBox_4.setGeometry(QtCore.QRect(420, 190, 401, 161))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(30, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(30, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.txtAdult = QtWidgets.QSpinBox(self.groupBox_4)
        self.txtAdult.setGeometry(QtCore.QRect(110, 40, 51, 31))
        self.txtAdult.setObjectName("txtAdult")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(210, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.txtChildren = QtWidgets.QSpinBox(self.groupBox_4)
        self.txtChildren.setGeometry(QtCore.QRect(110, 90, 51, 31))
        self.txtChildren.setObjectName("txtChildren")
        self.txtInfant = QtWidgets.QSpinBox(self.groupBox_4)
        self.txtInfant.setGeometry(QtCore.QRect(330, 40, 51, 31))
        self.txtInfant.setObjectName("txtInfant")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(210, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.txtSeniorCitizen = QtWidgets.QSpinBox(self.groupBox_4)
        self.txtSeniorCitizen.setGeometry(QtCore.QRect(330, 90, 51, 31))
        self.txtSeniorCitizen.setObjectName("txtSeniorCitizen")
        self.btnBookFlight = QtWidgets.QPushButton(self.tabBook)
        self.btnBookFlight.setGeometry(QtCore.QRect(230, 370, 331, 41))
        self.btnBookFlight.setObjectName("btnBookFlight")
        self.tabWidget.addTab(self.tabBook, "")
        self.tabStatus = QtWidgets.QWidget()
        self.tabStatus.setObjectName("tabStatus")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tabStatus)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 70, 154, 251))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_4.addWidget(self.label_29)
        self.label_37 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_4.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_4.addWidget(self.label_38)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tabStatus)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(170, 70, 181, 251))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblLocation = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.lblLocation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLocation.setObjectName("lblLocation")
        self.verticalLayout_5.addWidget(self.lblLocation)
        self.lblTravelDate = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.lblTravelDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTravelDate.setObjectName("lblTravelDate")
        self.verticalLayout_5.addWidget(self.lblTravelDate)
        self.lblPrice = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.lblPrice.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPrice.setObjectName("lblPrice")
        self.verticalLayout_5.addWidget(self.lblPrice)
        self.lblAvailSeats = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.lblAvailSeats.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAvailSeats.setObjectName("lblAvailSeats")
        self.verticalLayout_5.addWidget(self.lblAvailSeats)
        self.lblRemarks = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.lblRemarks.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblRemarks.setObjectName("lblRemarks")
        self.verticalLayout_5.addWidget(self.lblRemarks)
        self.label = QtWidgets.QLabel(self.tabStatus)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.label.setObjectName("label")
        self.cbxFlights = QtWidgets.QComboBox(self.tabStatus)
        self.cbxFlights.setGeometry(QtCore.QRect(110, 20, 231, 31))
        self.cbxFlights.setObjectName("cbxFlights")
        self.lstPassengers = QtWidgets.QListWidget(self.tabStatus)
        self.lstPassengers.setGeometry(QtCore.QRect(380, 40, 191, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstPassengers.setFont(font)
        self.lstPassengers.setObjectName("lstPassengers")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tabStatus)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(590, 40, 201, 311))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        self.lblFName = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lblFName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFName.setObjectName("lblFName")
        self.verticalLayout_8.addWidget(self.lblFName)
        self.label_39 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_8.addWidget(self.label_39)
        self.lblLName = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lblLName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLName.setObjectName("lblLName")
        self.verticalLayout_8.addWidget(self.lblLName)
        self.label_40 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_8.addWidget(self.label_40)
        self.lblGender = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lblGender.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblGender.setObjectName("lblGender")
        self.verticalLayout_8.addWidget(self.lblGender)
        self.label_41 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_8.addWidget(self.label_41)
        self.lblAge = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.lblAge.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAge.setObjectName("lblAge")
        self.verticalLayout_8.addWidget(self.lblAge)
        self.label_2 = QtWidgets.QLabel(self.tabStatus)
        self.label_2.setGeometry(QtCore.QRect(380, 10, 101, 31))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tabStatus, "")
        self.tabUserAccount = QtWidgets.QWidget()
        self.tabUserAccount.setObjectName("tabUserAccount")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tabUserAccount)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(40, 10, 281, 401))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_6.addWidget(self.label_36)
        self.lblUsername = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUsername.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUsername.setObjectName("lblUsername")
        self.verticalLayout_6.addWidget(self.lblUsername)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.lblUserFName = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUserFName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUserFName.setObjectName("lblUserFName")
        self.verticalLayout_6.addWidget(self.lblUserFName)
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_6.addWidget(self.label_30)
        self.lblUserLName = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUserLName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUserLName.setObjectName("lblUserLName")
        self.verticalLayout_6.addWidget(self.lblUserLName)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.lblEmail = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblEmail.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblEmail.setObjectName("lblEmail")
        self.verticalLayout_6.addWidget(self.lblEmail)
        self.label_45 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_6.addWidget(self.label_45)
        self.lblAddress = QtWidgets.QTextBrowser(self.verticalLayoutWidget_5)
        self.lblAddress.setObjectName("lblAddress")
        self.verticalLayout_6.addWidget(self.lblAddress)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tabUserAccount)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(340, 10, 271, 171))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_46 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_7.addWidget(self.label_46)
        self.lblBirthDate = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.lblBirthDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblBirthDate.setObjectName("lblBirthDate")
        self.verticalLayout_7.addWidget(self.lblBirthDate)
        self.label_47 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.verticalLayout_7.addWidget(self.label_47)
        self.lblUserGender = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.lblUserGender.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblUserGender.setObjectName("lblUserGender")
        self.verticalLayout_7.addWidget(self.lblUserGender)
        self.label_48 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_7.addWidget(self.label_48)
        self.lblNum = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.lblNum.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblNum.setObjectName("lblNum")
        self.verticalLayout_7.addWidget(self.lblNum)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabUserAccount)
        self.groupBox_5.setGeometry(QtCore.QRect(340, 200, 401, 211))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(50, 40, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(70, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(40, 120, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.txtCurrentPassword = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtCurrentPassword.setGeometry(QtCore.QRect(190, 40, 161, 31))
        self.txtCurrentPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtCurrentPassword.setObjectName("txtCurrentPassword")
        self.txtNewPassword = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtNewPassword.setGeometry(QtCore.QRect(190, 80, 161, 31))
        self.txtNewPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtNewPassword.setObjectName("txtNewPassword")
        self.txtConfirmPassword = QtWidgets.QLineEdit(self.groupBox_5)
        self.txtConfirmPassword.setGeometry(QtCore.QRect(190, 120, 161, 31))
        self.txtConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.btnChangePassword = QtWidgets.QPushButton(self.groupBox_5)
        self.btnChangePassword.setGeometry(QtCore.QRect(110, 160, 181, 41))
        self.btnChangePassword.setObjectName("btnChangePassword")
        self.tabWidget.addTab(self.tabUserAccount, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(CustomerWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CustomerWindow)

    def retranslateUi(self, CustomerWindow):
        _translate = QtCore.QCoreApplication.translate
        CustomerWindow.setWindowTitle(_translate("CustomerWindow", "Dialog"))
        self.groupBox.setTitle(_translate("CustomerWindow", "Origin"))
        self.label_3.setText(_translate("CustomerWindow", "Select A Country/ Region"))
        self.label_4.setText(_translate("CustomerWindow", "Select A City"))
        self.groupBox_2.setTitle(_translate("CustomerWindow", "Destination"))
        self.label_6.setText(_translate("CustomerWindow", "Select A Country/ Region"))
        self.label_7.setText(_translate("CustomerWindow", "Select A City"))
        self.groupBox_3.setTitle(_translate("CustomerWindow", "Travel Date"))
        self.label_9.setText(_translate("CustomerWindow", "From:"))
        self.label_10.setText(_translate("CustomerWindow", "Time:"))
        self.groupBox_4.setTitle(_translate("CustomerWindow", "Passenger(s)"))
        self.label_11.setText(_translate("CustomerWindow", "Adult:"))
        self.label_12.setText(_translate("CustomerWindow", "Children:"))
        self.label_13.setText(_translate("CustomerWindow", "Infant:"))
        self.label_14.setText(_translate("CustomerWindow", "Senior Citizen:"))
        self.btnBookFlight.setText(_translate("CustomerWindow", "Book A Flight"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBook), _translate("CustomerWindow", "Book A Flight"))
        self.label_15.setText(_translate("CustomerWindow", "Location:"))
        self.label_27.setText(_translate("CustomerWindow", "Travel Date:"))
        self.label_29.setText(_translate("CustomerWindow", "Flight Price:"))
        self.label_37.setText(_translate("CustomerWindow", "Available Seats:"))
        self.label_38.setText(_translate("CustomerWindow", "Remarks:"))
        self.lblLocation.setText(_translate("CustomerWindow", "<location>"))
        self.lblTravelDate.setText(_translate("CustomerWindow", "<travel date>"))
        self.lblPrice.setText(_translate("CustomerWindow", "<price>"))
        self.lblAvailSeats.setText(_translate("CustomerWindow", "<available seats>"))
        self.lblRemarks.setText(_translate("CustomerWindow", "<remarks>"))
        self.label.setText(_translate("CustomerWindow", "My Flights:"))
        self.label_16.setText(_translate("CustomerWindow", "First Name:"))
        self.lblFName.setText(_translate("CustomerWindow", "<Fname>"))
        self.label_39.setText(_translate("CustomerWindow", "Last Name:"))
        self.lblLName.setText(_translate("CustomerWindow", "<Lname>"))
        self.label_40.setText(_translate("CustomerWindow", "Gender:"))
        self.lblGender.setText(_translate("CustomerWindow", "<Gender>"))
        self.label_41.setText(_translate("CustomerWindow", "Age:"))
        self.lblAge.setText(_translate("CustomerWindow", "<Age>"))
        self.label_2.setText(_translate("CustomerWindow", "Passengers:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("CustomerWindow", "Flight Status"))
        self.tabUserAccount.setToolTip(_translate("CustomerWindow", "User Account"))
        self.label_36.setText(_translate("CustomerWindow", "Username:"))
        self.lblUsername.setText(_translate("CustomerWindow", "<username>"))
        self.label_8.setText(_translate("CustomerWindow", "First Name:"))
        self.lblUserFName.setText(_translate("CustomerWindow", "<Fname>"))
        self.label_30.setText(_translate("CustomerWindow", "Last Name:"))
        self.lblUserLName.setText(_translate("CustomerWindow", "<Lname>"))
        self.label_31.setText(_translate("CustomerWindow", "Email:"))
        self.lblEmail.setText(_translate("CustomerWindow", "<Email>"))
        self.label_45.setText(_translate("CustomerWindow", "Address:"))
        self.label_46.setText(_translate("CustomerWindow", "Birth Date:"))
        self.lblBirthDate.setText(_translate("CustomerWindow", "<Birthday>"))
        self.label_47.setText(_translate("CustomerWindow", "Gender:"))
        self.lblUserGender.setText(_translate("CustomerWindow", "<Gender>"))
        self.label_48.setText(_translate("CustomerWindow", "Contact Number:"))
        self.lblNum.setText(_translate("CustomerWindow", "<Contact Num>"))
        self.groupBox_5.setTitle(_translate("CustomerWindow", "Change Password:"))
        self.label_5.setText(_translate("CustomerWindow", "Current Password:"))
        self.label_17.setText(_translate("CustomerWindow", "New Password:"))
        self.label_18.setText(_translate("CustomerWindow", "Confirm Password:"))
        self.btnChangePassword.setText(_translate("CustomerWindow", "Change Password"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUserAccount), _translate("CustomerWindow", "User Account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomerWindow = QtWidgets.QDialog()
    ui = Ui_CustomerWindow()
    ui.setupUi(CustomerWindow)
    CustomerWindow.show()
    sys.exit(app.exec_())

