# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ryu\Desktop\Airline Reservation System\UI\payment.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PaymentWindow(object):
    def setupUi(self, PaymentWindow):
        PaymentWindow.setObjectName("PaymentWindow")
        PaymentWindow.resize(377, 490)
        font = QtGui.QFont()
        font.setPointSize(14)
        PaymentWindow.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(PaymentWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(PaymentWindow)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtCardNum = QtWidgets.QLineEdit(PaymentWindow)
        self.txtCardNum.setObjectName("txtCardNum")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtCardNum)
        self.label_2 = QtWidgets.QLabel(PaymentWindow)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.cbxCard = QtWidgets.QComboBox(PaymentWindow)
        self.cbxCard.setObjectName("cbxCard")
        self.cbxCard.addItem("")
        self.cbxCard.addItem("")
        self.cbxCard.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbxCard)
        self.label_3 = QtWidgets.QLabel(PaymentWindow)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(PaymentWindow)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtCSC = QtWidgets.QLineEdit(PaymentWindow)
        self.txtCSC.setObjectName("txtCSC")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtCSC)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtExpDate = QtWidgets.QDateEdit(PaymentWindow)
        self.txtExpDate.setDateTime(QtCore.QDateTime(QtCore.QDate(2018, 12, 1), QtCore.QTime(0, 0, 0)))
        self.txtExpDate.setObjectName("txtExpDate")
        self.horizontalLayout.addWidget(self.txtExpDate)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.btnConfirmFlight = QtWidgets.QPushButton(PaymentWindow)
        self.btnConfirmFlight.setObjectName("btnConfirmFlight")
        self.gridLayout.addWidget(self.btnConfirmFlight, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(PaymentWindow)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lblOrigin = QtWidgets.QLabel(self.groupBox)
        self.lblOrigin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblOrigin.setObjectName("lblOrigin")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblOrigin)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lblDestination = QtWidgets.QLabel(self.groupBox)
        self.lblDestination.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDestination.setObjectName("lblDestination")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblDestination)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.lblTravelDate = QtWidgets.QLabel(self.groupBox)
        self.lblTravelDate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTravelDate.setObjectName("lblTravelDate")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblTravelDate)
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.lblPrice = QtWidgets.QLabel(self.groupBox)
        self.lblPrice.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPrice.setObjectName("lblPrice")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lblPrice)
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.lblTotalPrice = QtWidgets.QLabel(self.groupBox)
        self.lblTotalPrice.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTotalPrice.setObjectName("lblTotalPrice")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lblTotalPrice)
        self.lblPassengers = QtWidgets.QLabel(self.groupBox)
        self.lblPassengers.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPassengers.setObjectName("lblPassengers")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lblPassengers)
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.cbxTime = QtWidgets.QComboBox(self.groupBox)
        self.cbxTime.setObjectName("cbxTime")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cbxTime)
        self.gridLayout_2.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 10)

        self.retranslateUi(PaymentWindow)
        self.cbxCard.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PaymentWindow)

    def retranslateUi(self, PaymentWindow):
        _translate = QtCore.QCoreApplication.translate
        PaymentWindow.setWindowTitle(_translate("PaymentWindow", "Dialog"))
        self.label.setText(_translate("PaymentWindow", "Card Number:"))
        self.label_2.setText(_translate("PaymentWindow", "Card:"))
        self.cbxCard.setCurrentText(_translate("PaymentWindow", "Mastercard"))
        self.cbxCard.setItemText(0, _translate("PaymentWindow", "Mastercard"))
        self.cbxCard.setItemText(1, _translate("PaymentWindow", "Visa Card"))
        self.cbxCard.setItemText(2, _translate("PaymentWindow", "JBC"))
        self.label_3.setText(_translate("PaymentWindow", "Expiry Date:"))
        self.label_4.setText(_translate("PaymentWindow", "CSC:"))
        self.txtExpDate.setDisplayFormat(_translate("PaymentWindow", "M/yyyy"))
        self.btnConfirmFlight.setText(_translate("PaymentWindow", "Confirm Flight"))
        self.groupBox.setTitle(_translate("PaymentWindow", "Payment Details"))
        self.label_6.setText(_translate("PaymentWindow", "Origin:"))
        self.lblOrigin.setText(_translate("PaymentWindow", "<origin>"))
        self.label_23.setText(_translate("PaymentWindow", "Destination:"))
        self.lblDestination.setText(_translate("PaymentWindow", "<destination>"))
        self.label_22.setText(_translate("PaymentWindow", "Travel Date:"))
        self.lblTravelDate.setText(_translate("PaymentWindow", "<travel date>"))
        self.label_24.setText(_translate("PaymentWindow", "Price:"))
        self.lblPrice.setText(_translate("PaymentWindow", "<price>"))
        self.label_26.setText(_translate("PaymentWindow", "Passengers:"))
        self.label_25.setText(_translate("PaymentWindow", "Total Price:"))
        self.lblTotalPrice.setText(_translate("PaymentWindow", "<totalPrice>"))
        self.lblPassengers.setText(_translate("PaymentWindow", "<passengers>"))
        self.label_27.setText(_translate("PaymentWindow", "Travel Time:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PaymentWindow = QtWidgets.QDialog()
    ui = Ui_PaymentWindow()
    ui.setupUi(PaymentWindow)
    PaymentWindow.show()
    sys.exit(app.exec_())

