from dbHelper import dbHelper

db = dbHelper("db_FlightReservation.db")

#Create user table
cmd = '''CREATE TABLE USER(
    USERID INTEGER PRIMARY KEY AUTOINCREMENT, 
    FNAME TEXT NOT NULL, 
    LNAME TEXT NOT NULL, 
    EMAIL TEXT NOT NULL, 
    USERNAME TEXT NOT NULL UNIQUE, 
    PASSWORD TEXT NOT NULL,  
    ADDRESS TEXT NOT NULL,
    DATEBIRTH TEXT NOT NULL, 
    GENDER TEXT NOT NULL, 
    CONTACTNUM TEXT NOT NULL);'''
db.ExecuteCommand(cmd)

#Create flight table
cmd = '''CREATE TABLE FLIGHT(
    FLIGHTID INTEGER PRIMARY KEY AUTOINCREMENT, 
    ORIGINID INTEGER NOT NULL, 
    DESTINATIONID INTEGER NOT NULL, 
    PRICE REAL NOT NULL,  
    TRAVELDATE TEXT NOT NULL, 
    TRAVELTIME TEXT NOT NULL,
    REMARKS TEXT);'''
db.ExecuteCommand(cmd)

#Create location table
cmd = '''CREATE TABLE LOCATION(
    LOCATIONID INTEGER PRIMARY KEY AUTOINCREMENT, 
    COUNTRYID INTEGER NOT NULL, 
    CITYID INTEGER NOT NULL);'''
db.ExecuteCommand(cmd)

#Create country table
cmd = '''CREATE TABLE COUNTRY(
    COUNTRYID INTEGER PRIMARY KEY AUTOINCREMENT, 
    COUNTRYNAME TEXT NOT NULL UNIQUE);'''
db.ExecuteCommand(cmd)

#Create city table
cmd = '''CREATE TABLE CITY(
    CITYID INTEGER PRIMARY KEY AUTOINCREMENT, 
    CITYNAME TEXT NOT NULL UNIQUE);'''
db.ExecuteCommand(cmd)

#Create passenger table
cmd = '''CREATE TABLE PASSENGER(
    PASSENGERID INTEGER PRIMARY KEY AUTOINCREMENT, 
    FNAME TEXT NOT NULL, 
    LNAME TEXT NOT NULL, 
    GENDER TEXT NOT NULL, 
    AGE TEXT NOT NULL,
    FLIGHTID INTERGER NOT NULL,
    USERID INTEGER NOT NULL);'''
db.ExecuteCommand(cmd)

#Create payments table
cmd = '''CREATE TABLE PAYMENT(
    PAYMENTID INTEGER PRIMARY KEY AUTOINCREMENT, 
    USERID INTEGER NOT NULL,
    CARDNUMBER TEXT NOT NULL,
    CARD TYPE TEXT NOT NULL,
    EXPIRYDATE TEXT NOT NULL,
    CSC TEXT NOT NULL,
    TOTALPRICE REAL NOT NULL);'''
db.ExecuteCommand(cmd)

        
    
