# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Ryu\Desktop\Airline Reservation System\UI\admin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdminWindow(object):
    users = []
    flights = []
    passengers = []

    def setupUi(self, Dialog, dateFlightsClicked = None, userLoad = None, lstUsersClicked = None, deleteUserClicked = None, deleteFlightClicked = None, updateFlightClicked = None, deletePassengerClicked = None):
        Dialog.setObjectName("Dialog")
        Dialog.resize(549, 662)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 531, 641))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabStatus = QtWidgets.QWidget()
        self.tabStatus.setObjectName("tabStatus")
        self.gbFlightDetails = QtWidgets.QGroupBox(self.tabStatus)
        self.gbFlightDetails.setGeometry(QtCore.QRect(10, 10, 501, 581))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.gbFlightDetails.setFont(font)
        self.gbFlightDetails.setObjectName("gbFlightDetails")
        self.dateFlights = QtWidgets.QCalendarWidget(self.gbFlightDetails)
        self.dateFlights.setGeometry(QtCore.QRect(40, 50, 351, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateFlights.setFont(font)
        self.dateFlights.setMinimumDate(QtCore.QDate(2000, 9, 14))
        self.dateFlights.setGridVisible(True)
        self.dateFlights.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.dateFlights.setNavigationBarVisible(True)
        self.dateFlights.setDateEditEnabled(False)
        self.dateFlights.setObjectName("dateFlights")
        self.label = QtWidgets.QLabel(self.gbFlightDetails)
        self.label.setGeometry(QtCore.QRect(40, 310, 91, 31))
        self.label.setObjectName("label")
        self.cbxFlights = QtWidgets.QComboBox(self.gbFlightDetails)
        self.cbxFlights.setGeometry(QtCore.QRect(110, 310, 241, 31))
        self.cbxFlights.setObjectName("cbxFlights")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.gbFlightDetails)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 360, 141, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout.addWidget(self.label_26)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.gbFlightDetails)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(190, 360, 161, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblLocation = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblLocation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLocation.setObjectName("lblLocation")
        self.verticalLayout_3.addWidget(self.lblLocation)
        self.lblDeparture = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblDeparture.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblDeparture.setObjectName("lblDeparture")
        self.verticalLayout_3.addWidget(self.lblDeparture)
        self.lblArrival = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblArrival.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblArrival.setObjectName("lblArrival")
        self.verticalLayout_3.addWidget(self.lblArrival)
        self.lblPrice = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblPrice.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPrice.setObjectName("lblPrice")
        self.verticalLayout_3.addWidget(self.lblPrice)
        self.lblAvailSeats = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblAvailSeats.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAvailSeats.setObjectName("lblAvailSeats")
        self.verticalLayout_3.addWidget(self.lblAvailSeats)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.btnDeleteFlight = QtWidgets.QPushButton(self.gbFlightDetails)
        self.btnDeleteFlight.setGeometry(QtCore.QRect(360, 310, 121, 31))
        self.btnDeleteFlight.setObjectName("btnDeleteFlight")
        self.btnUpdateFlight = QtWidgets.QPushButton(self.gbFlightDetails)
        self.btnUpdateFlight.setGeometry(QtCore.QRect(360, 530, 91, 31))
        self.btnUpdateFlight.setObjectName("btnUpdateFlight")
        self.tabWidget.addTab(self.tabStatus, "")
        self.tabBook = QtWidgets.QWidget()
        self.tabBook.setObjectName("tabBook")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tabBook)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(330, 290, 171, 201))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblFName = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lblFName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblFName.setObjectName("lblFName")
        self.verticalLayout_5.addWidget(self.lblFName)
        self.lblLName = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lblLName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblLName.setObjectName("lblLName")
        self.verticalLayout_5.addWidget(self.lblLName)
        self.lblGender = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lblGender.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblGender.setObjectName("lblGender")
        self.verticalLayout_5.addWidget(self.lblGender)
        self.lblAge = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.lblAge.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblAge.setObjectName("lblAge")
        self.verticalLayout_5.addWidget(self.lblAge)
        self.lstPassengers = QtWidgets.QListWidget(self.tabBook)
        self.lstPassengers.setGeometry(QtCore.QRect(10, 290, 191, 301))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstPassengers.setFont(font)
        self.lstPassengers.setObjectName("lstPassengers")
        self.label_3 = QtWidgets.QLabel(self.tabBook)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 61, 31))
        self.label_3.setObjectName("label_3")
        self.cbxFlightPassengers = QtWidgets.QComboBox(self.tabBook)
        self.cbxFlightPassengers.setGeometry(QtCore.QRect(90, 240, 241, 31))
        self.cbxFlightPassengers.setObjectName("cbxFlightPassengers")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tabBook)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(210, 290, 111, 201))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_4.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_4.addWidget(self.label_29)
        self.dateFlightPassengers = QtWidgets.QCalendarWidget(self.tabBook)
        self.dateFlightPassengers.setGeometry(QtCore.QRect(10, 10, 341, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateFlightPassengers.setFont(font)
        self.dateFlightPassengers.setMinimumDate(QtCore.QDate(2000, 9, 14))
        self.dateFlightPassengers.setGridVisible(True)
        self.dateFlightPassengers.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.dateFlightPassengers.setNavigationBarVisible(True)
        self.dateFlightPassengers.setDateEditEnabled(False)
        self.dateFlightPassengers.setObjectName("dateFlightPassengers")
        self.btnDeletePassenger = QtWidgets.QPushButton(self.tabBook)
        self.btnDeletePassenger.setGeometry(QtCore.QRect(220, 560, 171, 31))
        self.btnDeletePassenger.setObjectName("btnDeletePassenger")
        self.tabWidget.addTab(self.tabBook, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.btnDeleteUser = QtWidgets.QPushButton(self.tab_3)
        self.btnDeleteUser.setGeometry(QtCore.QRect(280, 560, 171, 31))
        self.btnDeleteUser.setObjectName("btnDeleteUser")
        self.lstUsers = QtWidgets.QListWidget(self.tab_3)
        self.lstUsers.setGeometry(QtCore.QRect(10, 10, 211, 581))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lstUsers.setFont(font)
        self.lstUsers.setObjectName("lstUsers")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(230, 10, 281, 541))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_36 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_6.addWidget(self.label_36)
        self.lblUsername = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUsername.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUsername.setObjectName("lblUsername")
        self.verticalLayout_6.addWidget(self.lblUsername)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.lblUserFName = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUserFName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUserFName.setObjectName("lblUserFName")
        self.verticalLayout_6.addWidget(self.lblUserFName)
        self.label_30 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_6.addWidget(self.label_30)
        self.lblUserLName = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUserLName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUserLName.setObjectName("lblUserLName")
        self.verticalLayout_6.addWidget(self.lblUserLName)
        self.label_31 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.lblEmail = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblEmail.setAlignment(QtCore.Qt.AlignCenter)
        self.lblEmail.setObjectName("lblEmail")
        self.verticalLayout_6.addWidget(self.lblEmail)
        self.label_32 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.lblAddress = QtWidgets.QTextBrowser(self.verticalLayoutWidget_5)
        self.lblAddress.setObjectName("lblAddress")
        self.verticalLayout_6.addWidget(self.lblAddress)
        self.label_33 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_6.addWidget(self.label_33)
        self.lblBirthDate = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblBirthDate.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBirthDate.setObjectName("lblBirthDate")
        self.verticalLayout_6.addWidget(self.lblBirthDate)
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_6.addWidget(self.label_34)
        self.lblUserGender = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblUserGender.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUserGender.setObjectName("lblUserGender")
        self.verticalLayout_6.addWidget(self.lblUserGender)
        self.label_35 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_6.addWidget(self.label_35)
        self.lblNum = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.lblNum.setAlignment(QtCore.Qt.AlignCenter)
        self.lblNum.setObjectName("lblNum")
        self.verticalLayout_6.addWidget(self.lblNum)
        self.tabWidget.addTab(self.tab_3, "")
        
        ######################### Load Items #################################
        self.Display(userLoad)
        self.lstUsers.currentItemChanged.connect(lstUsersClicked)


        ######################### Button Event ###############################
        self.dateFlights.clicked.connect(dateFlightsClicked)
        self.date = self.dateFlights.selectedDate()
        # self.btnDeleteFlight.clicked.connect(deleteFlightClicked)
        # self.btnUpdateFlight.clicked.connect(updateFlightClicked)
        # self.btnDeletePassenger.clicked.connect(deletePassengerClicked)
        self.btnDeleteUser.clicked.connect(deleteUserClicked)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Admin Window"))
        self.gbFlightDetails.setTitle(_translate("Dialog", "Flight Details"))
        self.label.setText(_translate("Dialog", "Flights:"))
        self.label_5.setText(_translate("Dialog", "Location:"))
        self.label_22.setText(_translate("Dialog", "Departure:"))
        self.label_23.setText(_translate("Dialog", "Arrival:"))
        self.label_24.setText(_translate("Dialog", "Price:"))
        self.label_25.setText(_translate("Dialog", "Available Seats:"))
        self.label_26.setText(_translate("Dialog", "Remarks:"))
        self.lblLocation.setText(_translate("Dialog", "<location>"))
        self.lblDeparture.setText(_translate("Dialog", "<departure>"))
        self.lblArrival.setText(_translate("Dialog", "<arrival>"))
        self.lblPrice.setText(_translate("Dialog", "<price>"))
        self.lblAvailSeats.setText(_translate("Dialog", "<available seats>"))
        self.btnDeleteFlight.setText(_translate("Dialog", "Delete Flight"))
        self.btnUpdateFlight.setText(_translate("Dialog", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("Dialog", "Manage Flights"))
        self.lblFName.setText(_translate("Dialog", "<Fname>"))
        self.lblLName.setText(_translate("Dialog", "<Lname>"))
        self.lblGender.setText(_translate("Dialog", "<Gender>"))
        self.lblAge.setText(_translate("Dialog", "<Age>"))
        self.label_3.setText(_translate("Dialog", "Flights:"))
        self.label_6.setText(_translate("Dialog", "First Name:"))
        self.label_27.setText(_translate("Dialog", "Last Name:"))
        self.label_28.setText(_translate("Dialog", "Gender:"))
        self.label_29.setText(_translate("Dialog", "Age:"))
        self.btnDeletePassenger.setText(_translate("Dialog", "Delete Passenger"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBook), _translate("Dialog", "Manage Passengers"))
        self.btnDeleteUser.setText(_translate("Dialog", "Delete User"))
        self.label_36.setText(_translate("Dialog", "Username:"))
        self.lblUsername.setText(_translate("Dialog", "<username>"))
        self.label_7.setText(_translate("Dialog", "First Name:"))
        self.lblUserFName.setText(_translate("Dialog", "<Fname>"))
        self.label_30.setText(_translate("Dialog", "Last Name:"))
        self.lblUserLName.setText(_translate("Dialog", "<Lname>"))
        self.label_31.setText(_translate("Dialog", "Email:"))
        self.lblEmail.setText(_translate("Dialog", "<Email>"))
        self.label_32.setText(_translate("Dialog", "Address:"))
        self.label_33.setText(_translate("Dialog", "Birth Date:"))
        self.lblBirthDate.setText(_translate("Dialog", "<Birthday>"))
        self.label_34.setText(_translate("Dialog", "Gender:"))
        self.lblUserGender.setText(_translate("Dialog", "<Gender>"))
        self.label_35.setText(_translate("Dialog", "Contact Number:"))
        self.lblNum.setText(_translate("Dialog", "<Contact Num>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Manage Users"))

    def Display(self, userLoad):
        # self.lstUsers.takeItem(self.lstUsers.currentRow())
        # self.lstUsers.clear()
        #self.users = []
        if userLoad is not None:
            for user in userLoad:
                item = QtWidgets.QListWidgetItem(str(user[4]))
                self.lstUsers.addItem(item)
                self.users.append(user[0])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_AdminWindow()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

