# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CustomerWindow(object):
    
    def setUserID(self, userID):
        global __userID
        __userID = userID

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(858, 742)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 831, 721))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabBook = QtWidgets.QWidget()
        self.tabBook.setObjectName("tabBook")
        self.radioButton = QtWidgets.QRadioButton(self.tabBook)
        self.radioButton.setGeometry(QtCore.QRect(270, 20, 141, 41))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tabBook)
        self.radioButton_2.setGeometry(QtCore.QRect(420, 20, 141, 41))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox = QtWidgets.QGroupBox(self.tabBook)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 381, 171))
        self.groupBox.setObjectName("groupBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 120, 341, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(20, 60, 341, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabBook)
        self.groupBox_2.setGeometry(QtCore.QRect(420, 70, 381, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 120, 341, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 60, 341, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabBook)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 260, 331, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEdit.setGeometry(QtCore.QRect(100, 40, 211, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEdit_2.setGeometry(QtCore.QRect(100, 90, 211, 31))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabBook)
        self.groupBox_4.setGeometry(QtCore.QRect(370, 260, 431, 161))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(30, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(30, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox.setGeometry(QtCore.QRect(110, 40, 51, 31))
        self.spinBox.setObjectName("spinBox")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(210, 40, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_2.setGeometry(QtCore.QRect(110, 90, 51, 31))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_3.setGeometry(QtCore.QRect(330, 40, 51, 31))
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(210, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_4.setGeometry(QtCore.QRect(330, 90, 51, 31))
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_15 = QtWidgets.QLabel(self.tabBook)
        self.label_15.setGeometry(QtCore.QRect(430, 540, 101, 31))
        self.label_15.setObjectName("label_15")
        self.label = QtWidgets.QLabel(self.tabBook)
        self.label.setGeometry(QtCore.QRect(30, 430, 91, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tabBook)
        self.label_2.setGeometry(QtCore.QRect(430, 460, 101, 31))
        self.label_2.setObjectName("label_2")
        self.listWidget = QtWidgets.QListWidget(self.tabBook)
        self.listWidget.setGeometry(QtCore.QRect(30, 470, 371, 181))
        self.listWidget.setObjectName("listWidget")
        self.label_16 = QtWidgets.QLabel(self.tabBook)
        self.label_16.setGeometry(QtCore.QRect(430, 580, 101, 31))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tabBook)
        self.label_17.setGeometry(QtCore.QRect(430, 500, 101, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tabBook)
        self.label_18.setGeometry(QtCore.QRect(430, 620, 141, 31))
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.tabBook, "")
        self.tabStatus = QtWidgets.QWidget()
        self.tabStatus.setObjectName("tabStatus")
        self.tabWidget.addTab(self.tabStatus, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton.setText(_translate("Dialog", "Round Trip"))
        self.radioButton_2.setText(_translate("Dialog", "One-Way"))
        self.groupBox.setTitle(_translate("Dialog", "Origin"))
        self.label_3.setText(_translate("Dialog", "Select A Country/ Region"))
        self.label_4.setText(_translate("Dialog", "Select A City"))
        self.groupBox_2.setTitle(_translate("Dialog", "Destination"))
        self.label_6.setText(_translate("Dialog", "Select A Country/ Region"))
        self.label_7.setText(_translate("Dialog", "Select A City"))
        self.groupBox_3.setTitle(_translate("Dialog", "Travel Dates"))
        self.label_9.setText(_translate("Dialog", "From:"))
        self.label_10.setText(_translate("Dialog", "Returning:"))
        self.groupBox_4.setTitle(_translate("Dialog", "Passenger(s)"))
        self.label_11.setText(_translate("Dialog", "Adult:"))
        self.label_12.setText(_translate("Dialog", "Children:"))
        self.label_13.setText(_translate("Dialog", "Infant:"))
        self.label_14.setText(_translate("Dialog", "Senior Citizen:"))
        self.label_15.setText(_translate("Dialog", "Arrival:"))
        self.label.setText(_translate("Dialog", "Flights:"))
        self.label_2.setText(_translate("Dialog", "Location:"))
        self.label_16.setText(_translate("Dialog", "Price:"))
        self.label_17.setText(_translate("Dialog", "Departure:"))
        self.label_18.setText(_translate("Dialog", "Available Seats:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBook), _translate("Dialog", "Book A Flight"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatus), _translate("Dialog", "Flight Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_CustomerWindow()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

